version: "3"
services:
  nginx:
    env_file: ../.env
    build: 
      context: config/nginx
    volumes:
      - ../.:/var/www/html
  php:
    env_file: ../.env
    build: 
      context: config/php
      args: 
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ../.:/var/www/html
  mariadb:
    env_file: ../.env
    build: 
      context: config/mariadb
    volumes:
      - /root/.docker-persistence/$PERSISTANCE_FOLDER_NAME/mariadb/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}