version: "3"
services:
  nginx:
    env_file: ../.env
    build: 
      context: config/nginx
    volumes:
      - ../.:/var/www/html
  php:
    env_file: ../.env
    build: 
      context: config/php
      args: 
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ../.:/var/www/html